### ISSUE TITLE
Export the snapshot of pages

### ISSUE THREAD

**Issue by owenchang1992** [owenchang1992/image_tagger#6]
# Description
For now, the only way to get the snapshot is to click the snapshot button on the individual page, in some situations, people may want to export all snapshots of the pages

## Solution
1. Add a button that can export the snapshot with a click

## TODO
1. Extract the drawing tags function
  - [ ] Check the dependencies of drawing tags function
  - [ ] Decouple drawing tags function and move it to utils.js
  - [ ] Add unit test for it

2. Extract the converting format function
 - Can extract from canvas.js?
